# Site settings
title: Jirawat Boonkumnerd
# generate from https://www.svgbackgrounds.com/
header-img: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 2000 1500'%3E%3Cdefs%3E%3Crect stroke='%23000000' stroke-width='0.12' width='1' height='1' id='s'/%3E%3Cpattern id='a' width='3' height='3' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cuse fill='%23050505' href='%23s' y='2'/%3E%3Cuse fill='%23050505' href='%23s' x='1' y='2'/%3E%3Cuse fill='%230a0a0a' href='%23s' x='2' y='2'/%3E%3Cuse fill='%230a0a0a' href='%23s'/%3E%3Cuse fill='%230f0f0f' href='%23s' x='2'/%3E%3Cuse fill='%230f0f0f' href='%23s' x='1' y='1'/%3E%3C/pattern%3E%3Cpattern id='b' width='7' height='11' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23141414'%3E%3Cuse href='%23s'/%3E%3Cuse href='%23s' y='5' /%3E%3Cuse href='%23s' x='1' y='10'/%3E%3Cuse href='%23s' x='2' y='1'/%3E%3Cuse href='%23s' x='2' y='4'/%3E%3Cuse href='%23s' x='3' y='8'/%3E%3Cuse href='%23s' x='4' y='3'/%3E%3Cuse href='%23s' x='4' y='7'/%3E%3Cuse href='%23s' x='5' y='2'/%3E%3Cuse href='%23s' x='5' y='6'/%3E%3Cuse href='%23s' x='6' y='9'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='h' width='5' height='13' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23141414'%3E%3Cuse href='%23s' y='5'/%3E%3Cuse href='%23s' y='8'/%3E%3Cuse href='%23s' x='1' y='1'/%3E%3Cuse href='%23s' x='1' y='9'/%3E%3Cuse href='%23s' x='1' y='12'/%3E%3Cuse href='%23s' x='2'/%3E%3Cuse href='%23s' x='2' y='4'/%3E%3Cuse href='%23s' x='3' y='2'/%3E%3Cuse href='%23s' x='3' y='6'/%3E%3Cuse href='%23s' x='3' y='11'/%3E%3Cuse href='%23s' x='4' y='3'/%3E%3Cuse href='%23s' x='4' y='7'/%3E%3Cuse href='%23s' x='4' y='10'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='c' width='17' height='13' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%231a1a1a'%3E%3Cuse href='%23s' y='11'/%3E%3Cuse href='%23s' x='2' y='9'/%3E%3Cuse href='%23s' x='5' y='12'/%3E%3Cuse href='%23s' x='9' y='4'/%3E%3Cuse href='%23s' x='12' y='1'/%3E%3Cuse href='%23s' x='16' y='6'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='d' width='19' height='17' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23000000'%3E%3Cuse href='%23s' y='9'/%3E%3Cuse href='%23s' x='16' y='5'/%3E%3Cuse href='%23s' x='14' y='2'/%3E%3Cuse href='%23s' x='11' y='11'/%3E%3Cuse href='%23s' x='6' y='14'/%3E%3C/g%3E%3Cg fill='%231f1f1f'%3E%3Cuse href='%23s' x='3' y='13'/%3E%3Cuse href='%23s' x='9' y='7'/%3E%3Cuse href='%23s' x='13' y='10'/%3E%3Cuse href='%23s' x='15' y='4'/%3E%3Cuse href='%23s' x='18' y='1'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='e' width='47' height='53' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23fffcfc'%3E%3Cuse href='%23s' x='2' y='5'/%3E%3Cuse href='%23s' x='16' y='38'/%3E%3Cuse href='%23s' x='46' y='42'/%3E%3Cuse href='%23s' x='29' y='20'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='f' width='59' height='71' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23fffcfc'%3E%3Cuse href='%23s' x='33' y='13'/%3E%3Cuse href='%23s' x='27' y='54'/%3E%3Cuse href='%23s' x='55' y='55'/%3E%3C/g%3E%3C/pattern%3E%3Cpattern id='g' width='139' height='97' patternUnits='userSpaceOnUse' patternTransform='scale(42.85) translate(-976.66 -732.5)'%3E%3Cg fill='%23fffcfc'%3E%3Cuse href='%23s' x='11' y='8'/%3E%3Cuse href='%23s' x='51' y='13'/%3E%3Cuse href='%23s' x='17' y='73'/%3E%3Cuse href='%23s' x='99' y='57'/%3E%3C/g%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23a)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23b)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23h)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23c)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23d)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23e)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23f)' width='100%25' height='100%25'/%3E%3Crect fill='url(%23g)' width='100%25' height='100%25'/%3E%3C/svg%3E
email: jo06942@gmail.com
description: "A Software Engineer"
keyword: "Full-Stack Developer, Programming, Machine Learning, IoT"
url: "https://ntsd.dev" # host for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
permalink: /:title/
paginate: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
future: true # Publish posts or collection documents with a future date.

# SNS settings
RSS: false
github_username: ntsd
# twitter_username: ntsd_me
# facebook_username: jo.ntsd
linkedin_username: ntsd
# github_btn: ntsd.github.io # Github repository name

# Config compress html
# documents: https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-lazy-load-image

# Lazyload all images https://github.com/kenchan0130/jekyll-lazy-load-image
lazy_load_image:
  src_attr_name: src
  additional_attrs:
    "loading": "lazy"

# Seo Tag setting
# document: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
defaults:
  - scope:
      path: ""
    values:
      image: /pwa/icons/512.png
logo: /pwa/icons/512.png
twitter:
  username: ntsd_me
  card: summary
facebook:
  app_id: 523337598616322
  publisher: ntsd.dev
  admins: jo.ntsd
social:
  name: Jirawat Boonkumnerd
  links:
    - https://web.facebook.com/ntsd.dev
    - https://github.com/ntsd
    - https://www.linkedin.com/in/ntsd

# Markdown settings
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important

# Giscus
giscus: true

# Google Analytics
# ga_track_id: 'UA-166826202-1' # Format: UA-xxxxxx-xx
# ga_domain: ntsd.dev

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "<h4>Jirawat Boonkumnerd</h4> A Software Engineer"
# sidebar-avatar: /img/me.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
